package cresec.mcp

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "laptop-default" (sha256:0f07a713e235504e5e02f4ac67064546fe70920760810931c3e15e88f3107929). Do not edit.
# Input:    {"server": "...", "tool": "...", "args": {...}, "args_bytes": 123}
# Decision: {"allow": bool, "action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool, "deny_reason": "..."}

default_action := "allow"

rules := [
	{"id": "no-exfil", "action": "deny", "reason": "no outbound HTTP"},
	{"id": "hold-writes", "action": "hold", "reason": "writes need a human"},
]

# no-exfil
rule_matches contains 0 if {
	glob.match("*", ["/"], input.server)
	some p in ["http_post", "send_*"]
	glob.match(p, ["/"], input.tool)
	v0 := object.get(input.args, ["url"], null)
	v0 != null
	type_name(v0) in {"string", "number", "boolean"}
	regex.match("^https?://", scalar_text(v0))
	input.args_bytes <= 65536
}

# hold-writes
rule_matches contains 1 if {
	glob.match("*", ["/"], input.server)
	glob.match("write_*", ["/"], input.tool)
}

# The exact text the TypeScript engine matches on: strings as-is, numbers and
# booleans through json.marshal (Go formats them exactly like JavaScript String()).
scalar_text(v) := v if is_string(v)

scalar_text(v) := json.marshal(v) if not is_string(v)

first_match := min(rule_matches) if count(rule_matches) > 0

# "rule <id>: <reason>" ("rule <id>" without a reason) when the action is not allow, "" otherwise.
deny_reason(rule) := "" if rule.action == "allow"

deny_reason(rule) := sprintf("rule %s", [rule.id]) if {
	rule.action != "allow"
	rule.reason == ""
}

deny_reason(rule) := sprintf("rule %s: %s", [rule.id, rule.reason]) if {
	rule.action != "allow"
	rule.reason != ""
}

decision := {
	"allow": rule.action == "allow",
	"action": rule.action,
	"rule_id": rule.id,
	"reason": rule.reason,
	"matched": true,
	"deny_reason": deny_reason(rule),
} if {
	count(rule_matches) > 0
	rule := rules[first_match]
}

decision := {
	"allow": default_action == "allow",
	"action": default_action,
	"rule_id": "",
	"reason": "",
	"matched": false,
	"deny_reason": default_deny_reason,
} if count(rule_matches) == 0

# "default <action>" when no rule matched and the section default is not allow, "" otherwise.
default_deny_reason := "" if default_action == "allow"

default_deny_reason := sprintf("default %s", [default_action]) if default_action != "allow"
