package cresec.mcp

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "credentials-example" (sha256:d2f32050be98dc858d5cf9834ba6b97bab132d57149cb45a6faec005d1d75784). Do not edit.
# Input:    {"server": "...", "tool": "...", "args": {...}, "args_bytes": 123}
# Decision: {"allow": bool, "action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool, "deny_reason": "..."}

default_action := "deny"

rules := [
	{"id": "github-writes", "action": "allow", "reason": ""},
	{"id": "reads", "action": "allow", "reason": ""},
]

# github-writes
rule_matches contains 0 if {
	regex.match("^corp\\-notes$", input.server)
	some p in ["^http_post$", "^http_delete$"]
	regex.match(p, input.tool)
}

# reads
rule_matches contains 1 if {
	regex.match("^[^\\/]*$", input.server)
	regex.match("^read_[^\\/]*$", input.tool)
}

first_match := min(rule_matches) if count(rule_matches) > 0

# "rule <id>: <reason>" ("rule <id>" without a reason) when the action is not allow, "" otherwise.
deny_reason(rule) := "" if rule.action == "allow"

deny_reason(rule) := sprintf("rule %s", [rule.id]) if {
	rule.action != "allow"
	rule.reason == ""
}

deny_reason(rule) := sprintf("rule %s: %s", [rule.id, rule.reason]) if {
	rule.action != "allow"
	rule.reason != ""
}

decision := {
	"allow": rule.action == "allow",
	"action": rule.action,
	"rule_id": rule.id,
	"reason": rule.reason,
	"matched": true,
	"deny_reason": deny_reason(rule),
} if {
	count(rule_matches) > 0
	rule := rules[first_match]
}

decision := {
	"allow": default_action == "allow",
	"action": default_action,
	"rule_id": "",
	"reason": "",
	"matched": false,
	"deny_reason": default_deny_reason,
} if count(rule_matches) == 0

# "default <action>" when no rule matched and the section default is not allow, "" otherwise.
default_deny_reason := "" if default_action == "allow"

default_deny_reason := sprintf("default %s", [default_action]) if default_action != "allow"
