package cresec.gateway.egress

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "empty" (sha256:313df9fa9255ded1c9f78c0b62353c6103952896261c3924fced307c9f0d6061). Do not edit.
# Input:    {"host": "...", "method": "GET", "path": "/...", "body_bytes": 123}
# Decision: {"action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool}

default_action := "deny"

rules := []

# No rules: nothing ever matches.
rule_matches := set()

first_match := min(rule_matches) if count(rule_matches) > 0

decision := {"action": rules[first_match].action, "rule_id": rules[first_match].id, "reason": rules[first_match].reason, "matched": true} if count(rule_matches) > 0

decision := {"action": default_action, "rule_id": "", "reason": "", "matched": false} if count(rule_matches) == 0
