package cresec.gateway.mcp

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "" (sha256:f87239dd75c044e03aa091adae89626d288dc2670e3e21d8c7b8d1021de4d3d6). Do not edit.
# Input:    {"server": "...", "tool": "...", "args": {...}, "args_bytes": 123}
# Decision: {"action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool}

default_action := "deny"

rules := [
	{"id": "rule[0]", "action": "allow", "reason": ""},
	{"id": "rule[1]", "action": "allow", "reason": "narrow search only"},
	{"id": "rule[2]", "action": "hold", "reason": "small unknown calls are held for review"},
]

# rule[0]
rule_matches contains 0 if {
	glob.match("corp-*", ["/"], input.server)
	glob.match("read_note", ["/"], input.tool)
}

# rule[1]
rule_matches contains 1 if {
	glob.match("*", ["/"], input.server)
	some p in ["list_notes", "search/**"]
	glob.match(p, ["/"], input.tool)
	v0 := object.get(input.args, ["filters", 0, "field"], null)
	v0 != null
	type_name(v0) in {"string", "number", "boolean"}
	regex.match("^(title|body)$", sprintf("%v", [v0]))
	v1 := object.get(input.args, ["limit"], null)
	v1 != null
	type_name(v1) in {"string", "number", "boolean"}
	regex.match("^[0-9]{1,2}$", sprintf("%v", [v1]))
	v2 := object.get(input.args, ["dry_run"], null)
	v2 != null
	type_name(v2) in {"string", "number", "boolean"}
	regex.match("^true$", sprintf("%v", [v2]))
}

# rule[2]
rule_matches contains 2 if {
	glob.match("*", ["/"], input.server)
	glob.match("*", ["/"], input.tool)
	input.args_bytes <= 1024
}

first_match := min(rule_matches) if count(rule_matches) > 0

decision := {"action": rules[first_match].action, "rule_id": rules[first_match].id, "reason": rules[first_match].reason, "matched": true} if count(rule_matches) > 0

decision := {"action": default_action, "rule_id": "", "reason": "", "matched": false} if count(rule_matches) == 0
