package cresec.credentials

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "credentials-example" (sha256:d2f32050be98dc858d5cf9834ba6b97bab132d57149cb45a6faec005d1d75784). Do not edit.
# Input:    {"credential": "...", "server": "...", "tool": "...", "host": "...", "host_source": "argument"|"declared"|"server_name", "path_template": "..."}
# Decision: {"allow": bool, "action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool, "deny_reason": "..."}
#
# Enforced BOTH locally (the gateway broker, before it swaps a synthetic for a real
# token) and here (the control plane, on /broker/exchange). The default is deny and is
# not author-settable: a use site that is not declared is not authorised. The shared
# decision shape above allows "hold"; a credentials decision never carries one.

default_action := "deny"

rules := [
	{"id": "github-issues/no-deletes", "action": "deny", "reason": "an issues token does not delete things"},
	{"id": "github-issues/create-issue", "action": "allow", "reason": ""},
	{"id": "clickup-api/tasks", "action": "allow", "reason": ""},
	{"id": "db-readonly/query", "action": "allow", "reason": ""},
	{"id": "npm-publish/publish", "action": "allow", "reason": ""},
	{"id": "stripe-readonly/charges", "action": "allow", "reason": ""},
]

# github-issues/no-deletes
rule_matches contains 0 if {
	input.credential == "github-issues"
	regex.match("^corp\\-notes$", input.server)
	regex.match("^http_delete$", input.tool)
	input.host_source == "argument"
	regex.match("^api\\.github\\.com$", input.host)
	input.path_template == input.tool
}

# github-issues/create-issue
rule_matches contains 1 if {
	input.credential == "github-issues"
	regex.match("^corp\\-notes$", input.server)
	regex.match("^http_post$", input.tool)
	input.host_source == "argument"
	some h in ["^api\\.github\\.com$", "^[^\\.]*\\.github\\.com$"]
	regex.match(h, input.host)
	input.path_template == input.tool
}

# clickup-api/tasks
rule_matches contains 2 if {
	input.credential == "clickup-api"
	regex.match("^clickup$", input.server)
	regex.match("^clickup_[^\\/]*$", input.tool)
	input.host_source == "declared"
	input.host == "api.clickup.com"
	regex.match("^901[^\\/]*$", input.path_template)
}

# db-readonly/query
rule_matches contains 3 if {
	input.credential == "db-readonly"
	regex.match("^db$", input.server)
	regex.match("^query$", input.tool)
	input.host_source == "server_name"
	regex.match("^db$", input.host)
	input.path_template == input.tool
}

# npm-publish/publish
rule_matches contains 4 if {
	input.credential == "npm-publish"
	regex.match("^npm$", input.server)
	regex.match("^publish$", input.tool)
	input.host_source == "declared"
	input.host == "registry.npmjs.org"
	input.path_template == input.tool
}

# stripe-readonly/charges
rule_matches contains 5 if {
	input.credential == "stripe-readonly"
	regex.match("^[^\\/]*$", input.server)
	regex.match("^stripe_[^\\/]*$", input.tool)
	input.host_source == "declared"
	input.host == "api.stripe.com"
	input.path_template == input.tool
}

first_match := min(rule_matches) if count(rule_matches) > 0

# "rule <id>: <reason>" ("rule <id>" without a reason) when the action is not allow, "" otherwise.
deny_reason(rule) := "" if rule.action == "allow"

deny_reason(rule) := sprintf("rule %s", [rule.id]) if {
	rule.action != "allow"
	rule.reason == ""
}

deny_reason(rule) := sprintf("rule %s: %s", [rule.id, rule.reason]) if {
	rule.action != "allow"
	rule.reason != ""
}

decision := {
	"allow": rule.action == "allow",
	"action": rule.action,
	"rule_id": rule.id,
	"reason": rule.reason,
	"matched": true,
	"deny_reason": deny_reason(rule),
} if {
	count(rule_matches) > 0
	rule := rules[first_match]
}

decision := {
	"allow": default_action == "allow",
	"action": default_action,
	"rule_id": "",
	"reason": "",
	"matched": false,
	"deny_reason": default_deny_reason,
} if count(rule_matches) == 0

# "default <action>" when no rule matched and the section default is not allow, "" otherwise.
default_deny_reason := "" if default_action == "allow"

default_deny_reason := sprintf("default %s", [default_action]) if default_action != "allow"
