package cresec.gateway.egress

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "laptop-default" (sha256:0f07a713e235504e5e02f4ac67064546fe70920760810931c3e15e88f3107929). Do not edit.
# Input:    {"host": "...", "method": "GET", "path": "/...", "body_bytes": 123}
# Decision: {"action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool}

default_action := "deny"

rules := [
	{"id": "github-read", "action": "allow", "reason": "read-only GitHub API"},
]

# github-read
rule_matches contains 0 if {
	glob.match("api.github.com", ["."], input.host)
	input.method in ["GET", "HEAD"]
	glob.match("/**", ["/"], input.path)
	input.body_bytes <= 1048576
}

first_match := min(rule_matches) if count(rule_matches) > 0

decision := {"action": rules[first_match].action, "rule_id": rules[first_match].id, "reason": rules[first_match].reason, "matched": true} if count(rule_matches) > 0

decision := {"action": default_action, "rule_id": "", "reason": "", "matched": false} if count(rule_matches) == 0
