package cresec.gateway.mcp

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "laptop-default" (sha256:0f07a713e235504e5e02f4ac67064546fe70920760810931c3e15e88f3107929). Do not edit.
# Input:    {"server": "...", "tool": "...", "args": {...}, "args_bytes": 123}
# Decision: {"action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool}

default_action := "allow"

rules := [
	{"id": "no-exfil", "action": "deny", "reason": "no outbound HTTP"},
	{"id": "hold-writes", "action": "hold", "reason": "writes need a human"},
]

# no-exfil
rule_matches contains 0 if {
	glob.match("*", ["/"], input.server)
	some p in ["http_post", "send_*"]
	glob.match(p, ["/"], input.tool)
	v0 := object.get(input.args, ["url"], null)
	v0 != null
	type_name(v0) in {"string", "number", "boolean"}
	regex.match("^https?://", sprintf("%v", [v0]))
	input.args_bytes <= 65536
}

# hold-writes
rule_matches contains 1 if {
	glob.match("*", ["/"], input.server)
	glob.match("write_*", ["/"], input.tool)
}

first_match := min(rule_matches) if count(rule_matches) > 0

decision := {"action": rules[first_match].action, "rule_id": rules[first_match].id, "reason": rules[first_match].reason, "matched": true} if count(rule_matches) > 0

decision := {"action": default_action, "rule_id": "", "reason": "", "matched": false} if count(rule_matches) == 0
