package cresec.mcp

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "" (sha256:f87239dd75c044e03aa091adae89626d288dc2670e3e21d8c7b8d1021de4d3d6). Do not edit.
# Input:    {"server": "...", "tool": "...", "args": {...}, "args_bytes": 123}
# Decision: {"allow": bool, "action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool, "deny_reason": "..."}

default_action := "deny"

rules := [
	{"id": "rule[0]", "action": "allow", "reason": ""},
	{"id": "rule[1]", "action": "allow", "reason": "narrow search only"},
	{"id": "rule[2]", "action": "hold", "reason": "small unknown calls are held for review"},
]

# rule[0]
rule_matches contains 0 if {
	regex.match("^corp\\-[^\\/]*$", input.server)
	regex.match("^read_note$", input.tool)
}

# rule[1]
rule_matches contains 1 if {
	regex.match("^[^\\/]*$", input.server)
	some p in ["^list_notes$", "^search\\/[\\s\\S]*$"]
	regex.match(p, input.tool)
	is_object(input.args)
	v0 := input.args.filters[0].field
	type_name(v0) in {"string", "number", "boolean"}
	regex.match("^(title|body)$", scalar_text(v0))
	v1 := input.args.limit
	type_name(v1) in {"string", "number", "boolean"}
	regex.match("^[0-9]{1,2}$", scalar_text(v1))
	v2 := input.args.dry_run
	type_name(v2) in {"string", "number", "boolean"}
	regex.match("^true$", scalar_text(v2))
}

# rule[2]
rule_matches contains 2 if {
	regex.match("^[^\\/]*$", input.server)
	regex.match("^[^\\/]*$", input.tool)
	input.args_bytes <= 1024
}

# The exact text the TypeScript engine matches on: strings as-is, numbers and
# booleans through json.marshal (Go formats them exactly like JavaScript String()).
scalar_text(v) := v if is_string(v)

scalar_text(v) := json.marshal(v) if not is_string(v)

first_match := min(rule_matches) if count(rule_matches) > 0

# "rule <id>: <reason>" ("rule <id>" without a reason) when the action is not allow, "" otherwise.
deny_reason(rule) := "" if rule.action == "allow"

deny_reason(rule) := sprintf("rule %s", [rule.id]) if {
	rule.action != "allow"
	rule.reason == ""
}

deny_reason(rule) := sprintf("rule %s: %s", [rule.id, rule.reason]) if {
	rule.action != "allow"
	rule.reason != ""
}

decision := {
	"allow": rule.action == "allow",
	"action": rule.action,
	"rule_id": rule.id,
	"reason": rule.reason,
	"matched": true,
	"deny_reason": deny_reason(rule),
} if {
	count(rule_matches) > 0
	rule := rules[first_match]
}

decision := {
	"allow": default_action == "allow",
	"action": default_action,
	"rule_id": "",
	"reason": "",
	"matched": false,
	"deny_reason": default_deny_reason,
} if count(rule_matches) == 0

# "default <action>" when no rule matched and the section default is not allow, "" otherwise.
default_deny_reason := "" if default_action == "allow"

default_deny_reason := sprintf("default %s", [default_action]) if default_action != "allow"
