package cresec.gateway.egress

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "ci/egress.v1" (sha256:73eb972d96378ed05ae12fba39711e4f4f52eb67cc925d5c10d1b9bc5fc4d3f7). Do not edit.
# Input:    {"host": "...", "method": "GET", "path": "/...", "body_bytes": 123}
# Decision: {"action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool}

default_action := "deny"

rules := [
	{"id": "github", "action": "allow", "reason": ""},
	{"id": "npm-publish", "action": "hold", "reason": "publishing needs a human"},
	{"id": "telemetry", "action": "deny", "reason": "no telemetry"},
]

# github
rule_matches contains 0 if {
	some h in ["api.github.com", "*.githubusercontent.com"]
	glob.match(h, ["."], input.host)
	input.method in ["GET", "HEAD"]
	glob.match("/**", ["/"], input.path)
}

# npm-publish
rule_matches contains 1 if {
	glob.match("registry.npmjs.org", ["."], input.host)
	input.method in ["PUT"]
	glob.match("/-/**", ["/"], input.path)
	input.body_bytes <= 4096
}

# telemetry
rule_matches contains 2 if {
	glob.match("*.telemetry.*", ["."], input.host)
	some p in ["/v1/*", "/v2/**"]
	glob.match(p, ["/"], input.path)
}

first_match := min(rule_matches) if count(rule_matches) > 0

decision := {"action": rules[first_match].action, "rule_id": rules[first_match].id, "reason": rules[first_match].reason, "matched": true} if count(rule_matches) > 0

decision := {"action": default_action, "rule_id": "", "reason": "", "matched": false} if count(rule_matches) == 0
