package cresec.gateway.mcp

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "ci/egress.v1" (sha256:73eb972d96378ed05ae12fba39711e4f4f52eb67cc925d5c10d1b9bc5fc4d3f7). Do not edit.
# Input:    {"server": "...", "tool": "...", "args": {...}, "args_bytes": 123}
# Decision: {"action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool}

default_action := "allow"

rules := []

# No rules: nothing ever matches.
rule_matches := set()

first_match := min(rule_matches) if count(rule_matches) > 0

decision := {"action": rules[first_match].action, "rule_id": rules[first_match].id, "reason": rules[first_match].reason, "matched": true} if count(rule_matches) > 0

decision := {"action": default_action, "rule_id": "", "reason": "", "matched": false} if count(rule_matches) == 0
