package cresec.egress

import rego.v1

# Generated by mcp-recorder 0.0.0-test from policy "ci/egress.v1" (sha256:73eb972d96378ed05ae12fba39711e4f4f52eb67cc925d5c10d1b9bc5fc4d3f7). Do not edit.
# Input:    {"host": "...", "method": "GET", "path": "/...", "body_bytes": 123}
# Decision: {"allow": bool, "action": "allow"|"hold"|"deny", "rule_id": "...", "reason": "...", "matched": bool, "deny_reason": "..."}

default_action := "deny"

rules := [
	{"id": "github", "action": "allow", "reason": ""},
	{"id": "npm-publish", "action": "hold", "reason": "publishing needs a human"},
	{"id": "telemetry", "action": "deny", "reason": "no telemetry"},
]

# github
rule_matches contains 0 if {
	some h in ["api.github.com", "*.githubusercontent.com"]
	glob.match(h, ["."], input.host)
	input.method in ["GET", "HEAD"]
	glob.match("/**", ["/"], input.path)
}

# npm-publish
rule_matches contains 1 if {
	glob.match("registry.npmjs.org", ["."], input.host)
	input.method in ["PUT"]
	glob.match("/-/**", ["/"], input.path)
	input.body_bytes <= 4096
}

# telemetry
rule_matches contains 2 if {
	glob.match("*.telemetry.*", ["."], input.host)
	some p in ["/v1/*", "/v2/**"]
	glob.match(p, ["/"], input.path)
}

first_match := min(rule_matches) if count(rule_matches) > 0

# "rule <id>: <reason>" ("rule <id>" without a reason) when the action is not allow, "" otherwise.
deny_reason(rule) := "" if rule.action == "allow"

deny_reason(rule) := sprintf("rule %s", [rule.id]) if {
	rule.action != "allow"
	rule.reason == ""
}

deny_reason(rule) := sprintf("rule %s: %s", [rule.id, rule.reason]) if {
	rule.action != "allow"
	rule.reason != ""
}

decision := {
	"allow": rule.action == "allow",
	"action": rule.action,
	"rule_id": rule.id,
	"reason": rule.reason,
	"matched": true,
	"deny_reason": deny_reason(rule),
} if {
	count(rule_matches) > 0
	rule := rules[first_match]
}

decision := {
	"allow": default_action == "allow",
	"action": default_action,
	"rule_id": "",
	"reason": "",
	"matched": false,
	"deny_reason": default_deny_reason,
} if count(rule_matches) == 0

# "default <action>" when no rule matched and the section default is not allow, "" otherwise.
default_deny_reason := "" if default_action == "allow"

default_deny_reason := sprintf("default %s", [default_action]) if default_action != "allow"
